
name: Alpine Base Image Publish

on:
  workflow_dispatch:
  repository_dispatch:

jobs:
  publish:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v4
    
    - name: Setup Alpine Linux
      uses: jirutka/setup-alpine@v1

    - name: Get version of alpine
      id: getVersion
      run: |
        version=$(cat /etc/alpine-release)
        echo "curentVersion=$version" >> $GITHUB_OUTPUT
      shell: alpine.sh {0}
     
    - name: Login to Docker Hub
      uses: docker/login-action@v3
      with:
        username: ${{ secrets.DOCKER_HUB_USER }}
        password: ${{ secrets.DOCKER_HUB_TOKEN }}

    - name: Login to AliYun Registry
      uses: docker/login-action@v3
      with:
        registry: registry.cn-chengdu.aliyuncs.com
        username: ${{ secrets.ALIYUN_USER }}
        password: ${{ secrets.ALIYUN_TOKEN }}

    - name: Build and Push Docker images
      id: build
      uses: docker/build-push-action@v6
      with:
        file: Dockerfile
        context: .
        push: true
        tags: |
          clion007/alpine:latest
          clion007/alpine:${{ steps.getVersion.outputs.curentVersion }}
          registry.cn-chengdu.aliyuncs.com/clion/alpine:latest
          registry.cn-chengdu.aliyuncs.com/clion/alpine:${{ steps.getVersion.outputs.curentVersion }}
      
    - name: Publish Release
      if: steps.build.outcome == 'success'
      uses: ncipollo/release-action@v1
      with:
        name: Alpine Linux v${{ steps.getVersion.outputs.curentVersion }}
        tag: v${{ steps.getVersion.outputs.curentVersion }}
        
    - name: Delete workflow runs
      uses: Mattraks/delete-workflow-runs@v2
      with:
        retain_days: 0
        keep_minimum_runs: 2
