# Description: alpine version update checker

name: Alpine Update Checker

on:
  workflow_dispatch:
  schedule:
    - cron: 3 16 * * *

jobs:
  check:
    runs-on: ubuntu-latest

    steps:
    
    - name: Setup latest Alpine Linux
      uses: jirutka/setup-alpine@v1

    - name: Get latest version of alpine
      id: getVersion
      run: |
        version=$(cat /etc/alpine-release)
        echo "curentVersion=$version" >> $GITHUB_OUTPUT
      shell: alpine.sh {0}

    - name: Compare Alpine Version
      id: cacheVersion
      uses: actions/cache@v4
      with:
        path: .curentVersion
        key: ${{ steps.getVersion.outputs.curentVersion }}

    - name: Save New Curent Version
      if: steps.cacheVersion.outputs.cache-hit != 'true'
      run: |
        echo ${{ steps.getVersion.outputs.curentVersion }} | tee .curentVersion

    - name: Trigger build
      if: steps.cacheVersion.outputs.cache-hit != 'true'
      uses: peter-evans/repository-dispatch@v3
      with:
        event-type: Alpine Image Update
        
    - name: Delete workflow runs
      uses: Mattraks/delete-workflow-runs@v2
      with:
        retain_days: 0
        keep_minimum_runs: 2
